import { z } from 'zod'

/**
 * Workspace domain model.
 *
 * Zod schemas are the single source of truth: the TypeScript types are inferred
 * from them and the very same schemas validate everything that comes back from
 * `localStorage` or from an imported backup file. Invalid values fall back to a
 * safe default (`.catch`) instead of taking the whole app down.
 */

export const TASK_PRIORITIES = ['High', 'Medium', 'Low'] as const
export const TASK_STATUSES = ['Pending', 'In Progress', 'Completed'] as const
export const PROJECT_STATUSES = ['Planning', 'Active', 'Paused', 'Completed'] as const

export const UNASSIGNED_PROJECT = 'Unassigned'

export const taskPrioritySchema = z.enum(TASK_PRIORITIES)
export const taskStatusSchema = z.enum(TASK_STATUSES)
export const projectStatusSchema = z.enum(PROJECT_STATUSES)

export type TaskPriority = z.infer<typeof taskPrioritySchema>
export type TaskStatus = z.infer<typeof taskStatusSchema>
export type ProjectStatus = z.infer<typeof projectStatusSchema>

/** `YYYY-MM-DD`, or an empty string when no due date is set. */
export const isoDateSchema = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/)
  .or(z.literal(''))

export const taskSchema = z.object({
  id: z.string().min(1).max(64),
  title: z.string().trim().min(1).max(160),
  project: z.string().trim().max(80).catch(UNASSIGNED_PROJECT),
  priority: taskPrioritySchema.catch('Medium'),
  status: taskStatusSchema.catch('Pending'),
  dueDate: isoDateSchema.catch(''),
  createdAt: z.string().max(40).catch(() => new Date(0).toISOString()),
})

export const projectSchema = z.object({
  id: z.string().min(1).max(64),
  name: z.string().trim().min(1).max(80),
  description: z.string().trim().max(280).catch(''),
  status: projectStatusSchema.catch('Planning'),
  progress: z.coerce.number().int().min(0).max(100).catch(0),
  createdAt: z.string().max(40).catch(() => new Date(0).toISOString()),
})

export type Task = z.infer<typeof taskSchema>
export type Project = z.infer<typeof projectSchema>

/** Shape persisted in localStorage (versioned envelope). */
export const workspaceSnapshotSchema = z.object({
  tasks: z.array(taskSchema),
  projects: z.array(projectSchema),
})

export type WorkspaceSnapshot = z.infer<typeof workspaceSnapshotSchema>

/** Shape of an exported backup file. */
export const workspaceBackupSchema = z.object({
  app: z.literal('motif-productivity-suite').catch('motif-productivity-suite'),
  version: z.coerce.number().int().positive().catch(2),
  exportedAt: z.string().catch(() => new Date().toISOString()),
  // Required — importing a file that merely *looks* like JSON must never
  // silently replace the workspace with empty data.
  tasks: z.array(taskSchema),
  projects: z.array(projectSchema),
})

export type WorkspaceBackup = z.infer<typeof workspaceBackupSchema>

/** Input accepted by `addTask` (id + createdAt are generated by the store). */
export type NewTaskInput = Pick<Task, 'title' | 'project' | 'priority'> &
  Partial<Pick<Task, 'status' | 'dueDate'>>

/** Input accepted by `addProject` (id/progress/createdAt are generated). */
export type NewProjectInput = Pick<Project, 'name' | 'description' | 'status'>
